In [2]:
!wget https://raw.githubusercontent.com/Suyyala/learn-gpt/main/data/input.txt

--2023-07-05 21:24:08--  https://raw.githubusercontent.com/Suyyala/learn-gpt/main/data/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.03s   

2023-07-05 21:24:09 (30.5 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [3]:
with open('input.txt', 'r', encoding='utf-8') as f:
  text = f.read()

In [4]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

In [6]:
print(chars)
print(vocab_size)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
65


In [7]:
# tokenization
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
print(stoi)
print(itos)


{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i',

In [8]:
encode = lambda x: [stoi[ch] for ch in x]
decode = lambda x: "".join([itos[i] for i in x])
print(encode('hello world'))
print(decode(encode('hello world')))

[46, 43, 50, 50, 53, 1, 61, 53, 56, 50, 42]
hello world


In [9]:
!pip install tiktoken

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 25.9 MB/s eta 0:00:00


In [10]:
import tiktoken

In [11]:
tokenizer = tiktoken.get_encoding('gpt2')
print(f'vocab_size {tokenizer.n_vocab}')
print(tokenizer.encode("hello world"))
print(tokenizer.decode(tokenizer.encode('hello world')))


vocab_size 50257
[31373, 995]
hello world


In [12]:

# tokenize entire input data set
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])


torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [125]:
# create a fixed size sequences to input data - this would be context length we can feed
sequence_length = 6
batched_data = data.view(-1, sequence_length)
print(batched_data.shape)
print(batched_data[:10])


torch.Size([185899, 6])
tensor([[18, 47, 56, 57, 58,  1],
        [15, 47, 58, 47, 64, 43],
        [52, 10,  0, 14, 43, 44],
        [53, 56, 43,  1, 61, 43],
        [ 1, 54, 56, 53, 41, 43],
        [43, 42,  1, 39, 52, 63],
        [ 1, 44, 59, 56, 58, 46],
        [43, 56,  6,  1, 46, 43],
        [39, 56,  1, 51, 43,  1],
        [57, 54, 43, 39, 49,  8]])


In [126]:
# Lets create a training data examples from above data set
# each row in above set correspond to multiple traning examples to predict next chracter given previous characters
# we dont need future characters as input so we mask them

a = torch.ones(4, 5)
w = torch.tril(a)
print(w)
print(a)
c = torch.arange(start=1, end=6, step=1)
print(c)
print(c.shape)
d = c.expand(4, -1)
e = d * w
print(e)





tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1, 2, 3, 4, 5])
torch.Size([5])
tensor([[1., 0., 0., 0., 0.],
        [1., 2., 0., 0., 0.],
        [1., 2., 3., 0., 0.],
        [1., 2., 3., 4., 0.]])


In [127]:
# Create a lower triangular matrix of ones with dimensions (sequence_length, sequence_length)
mask = torch.tril(torch.ones(sequence_length, sequence_length))

# Expand the single row data to have multiple rows for each data sample and apply the mask
expanded_data = []
target_data = []
for single_row in batched_data:
    # Broadcast the single row
    broadcasted_row = single_row.expand(sequence_length, -1)
    # Apply the mask
    expanded_row = broadcasted_row * mask
    expanded_data.append(expanded_row)
    targets = single_row[1:]
    # Add an extra dummy target for the last sequence
    targets = torch.cat([targets, torch.tensor([0.0])])
    target_data.append(targets)

# Convert the list of expanded data to a tensor
expanded_data = torch.stack(expanded_data)
target_data = torch.stack(target_data)
print("Expanded data shape:", expanded_data.shape)
print(f"target data {target_data[:10]}")


Expanded data shape: torch.Size([185899, 6, 6])
target data tensor([[47., 56., 57., 58.,  1.,  0.],
        [47., 58., 47., 64., 43.,  0.],
        [10.,  0., 14., 43., 44.,  0.],
        [56., 43.,  1., 61., 43.,  0.],
        [54., 56., 53., 41., 43.,  0.],
        [42.,  1., 39., 52., 63.,  0.],
        [44., 59., 56., 58., 46.,  0.],
        [56.,  6.,  1., 46., 43.,  0.],
        [56.,  1., 51., 43.,  1.,  0.],
        [54., 43., 39., 49.,  8.,  0.]])


In [128]:
print(expanded_data[:3])
print(target_data[:3])

tensor([[[18.,  0.,  0.,  0.,  0.,  0.],
         [18., 47.,  0.,  0.,  0.,  0.],
         [18., 47., 56.,  0.,  0.,  0.],
         [18., 47., 56., 57.,  0.,  0.],
         [18., 47., 56., 57., 58.,  0.],
         [18., 47., 56., 57., 58.,  1.]],

        [[15.,  0.,  0.,  0.,  0.,  0.],
         [15., 47.,  0.,  0.,  0.,  0.],
         [15., 47., 58.,  0.,  0.,  0.],
         [15., 47., 58., 47.,  0.,  0.],
         [15., 47., 58., 47., 64.,  0.],
         [15., 47., 58., 47., 64., 43.]],

        [[52.,  0.,  0.,  0.,  0.,  0.],
         [52., 10.,  0.,  0.,  0.,  0.],
         [52., 10.,  0.,  0.,  0.,  0.],
         [52., 10.,  0., 14.,  0.,  0.],
         [52., 10.,  0., 14., 43.,  0.],
         [52., 10.,  0., 14., 43., 44.]]])
tensor([[47., 56., 57., 58.,  1.,  0.],
        [47., 58., 47., 64., 43.,  0.],
        [10.,  0., 14., 43., 44.,  0.]])


In [97]:
# merge these samples into batch dimension
train_data = expanded_data.view(-1, 6)
target_data = target_data.view(-1, 1)
print(train_data[:10])
print(target_data[:10])

tensor([[18.,  0.,  0.,  0.,  0.,  0.],
        [18., 47.,  0.,  0.,  0.,  0.],
        [18., 47., 56.,  0.,  0.,  0.],
        [18., 47., 56., 57.,  0.,  0.],
        [18., 47., 56., 57., 58.,  0.],
        [18., 47., 56., 57., 58.,  1.],
        [15.,  0.,  0.,  0.,  0.,  0.],
        [15., 47.,  0.,  0.,  0.,  0.],
        [15., 47., 58.,  0.,  0.,  0.],
        [15., 47., 58., 47.,  0.,  0.]])
tensor([[47.],
        [56.],
        [57.],
        [58.],
        [ 1.],
        [ 0.],
        [47.],
        [58.],
        [47.],
        [64.]])


In [98]:
print(train_data.shape, target_data.shape)

torch.Size([1115394, 6]) torch.Size([1115394, 1])


In [113]:
# introduce mini batch size
batch_size = 3
train_batch = train_data.view(batch_size, -1, 6)
target_batch = target_data.view(batch_size, -1, 1)
print(train_batch.shape, target_batch.shape)
print(train_batch[0,:10], target_batch[0,:10])

torch.Size([3, 371798, 6]) torch.Size([3, 371798, 1])
tensor([[18.,  0.,  0.,  0.,  0.,  0.],
        [18., 47.,  0.,  0.,  0.,  0.],
        [18., 47., 56.,  0.,  0.,  0.],
        [18., 47., 56., 57.,  0.,  0.],
        [18., 47., 56., 57., 58.,  0.],
        [18., 47., 56., 57., 58.,  1.],
        [15.,  0.,  0.,  0.,  0.,  0.],
        [15., 47.,  0.,  0.,  0.,  0.],
        [15., 47., 58.,  0.,  0.,  0.],
        [15., 47., 58., 47.,  0.,  0.]]) tensor([[47.],
        [56.],
        [57.],
        [58.],
        [ 1.],
        [ 0.],
        [47.],
        [58.],
        [47.],
        [64.]])


In [13]:
# instead of fixed size splits as sequence
# lets use random sampling offsets to generate traiin samples
n = int(0.9 * len(data))
print(n)
train_d = data[:n]
test_d = data[n:]
print(train_d.shape, test_d.shape)

1003854
torch.Size([1003854]) torch.Size([111540])


In [14]:
block_size = 8
batch_size = 4

def get_sampled_data(data_type = 'train'):
  data_set = train_d if data_type == 'train' else  test_d
  ix = torch.randint(low=0, high=len(data_set) - block_size, size=(batch_size, ))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x, y

x, y = get_sampled_data()
print(x.shape, y.shape)
print(x)
print(y)


torch.Size([4, 8]) torch.Size([4, 8])
tensor([[46, 43,  1, 46, 39, 58, 41, 46],
        [47, 57, 46,  1, 58, 46, 43, 51],
        [46,  1, 53, 56,  1, 50, 47, 44],
        [39, 57,  1, 51, 47, 57, 58, 39]])
tensor([[43,  1, 46, 39, 58, 41, 46, 43],
        [57, 46,  1, 58, 46, 43, 51,  1],
        [ 1, 53, 56,  1, 50, 47, 44, 43],
        [57,  1, 51, 47, 57, 58, 39, 49]])


In [67]:
import torch.nn as nn
from torch.nn import functional as F

class BigramModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embeddings_table = nn.Embedding(num_embeddings=vocab_size, embedding_dim=vocab_size)

  def forward(self, idx, targets=None):
    logits = self.token_embeddings_table(idx) # B, T, C
    if targets is None:
      return logits, None
    B, T, C = logits.shape
    logits = logits.view(B*T, C)
    targets = targets.view(B*T)
    loss = F.cross_entropy(logits, targets)
    return logits, loss

  def generate(self, idx, max_tokens):
    # B, T is indices of current context
    for i in range(max_tokens):
      logits, loss = self(idx)
      # get latest timestep logits
      logits = logits[:, -1, :] # B, latest Timestep, C
      probs = F.softmax(logits, dim=-1)
      id_next = torch.multinomial(probs, num_samples=1) # B, 1
      idx = torch.cat((idx, id_next), dim=1) # B, T+1
    return idx





In [68]:
print(vocab_size)
m = BigramModel(vocab_size=vocab_size)
logits, loss = m(x, y)
print(logits.shape, loss)
print(logits)


65
torch.Size([32, 65]) tensor(4.7176, grad_fn=<NllLossBackward0>)
tensor([[ 0.7525,  0.8070, -0.9034,  ..., -0.0399, -0.0135,  0.5220],
        [-1.6677, -0.9135, -0.1714,  ...,  0.3814, -0.9266, -0.3998],
        [-1.0928, -0.1715, -0.5418,  ..., -0.5209,  1.7078, -1.3630],
        ...,
        [ 0.6166, -0.0157,  0.5483,  ...,  0.9931, -0.2095,  1.2704],
        [ 0.5434,  1.1057,  2.1404,  ...,  1.6791, -1.7088,  0.3230],
        [ 0.2487, -0.1023, -0.7687,  ..., -1.0229,  1.0408,  0.7397]],
       grad_fn=<ViewBackward0>)


In [69]:
# training loop
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [90]:
batch_size = 32
for steps in range(1000):
  xb, yb = get_sampled_data()
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

2.45859694480896


In [92]:
decode(m.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_tokens=500)[0].tolist())

'\nwiaracan ng in,\nwounin nst st wn f t, ou:\n\nPevat, neinuse s, cas h\nI yorthode te,\nGLIfin by.\n\n\nF t r mer se pll: be t he mare othisHAbrthiteled s a mee angen qpure mor, counove p, to w; thather\nSOMAGlain,\n\nTOf The Prs toflout me har;\nTZXENTu m,\nBunth an fe.\nTor tiventh, towee.\nSe ig:\n\nF teryord hend sen rsbokeguive veiot d ie.\nPundrea CISt; horire al.\nENe, ch ou mm tukNG prakst dorernofo ame hipy b t l ICHace SANCos m iotok QG h hel s r\nBinarng, t Maimy chafor he hath wher f hino, mavir thorg sa'

In [41]:
# Attention head
from torch.nn import functional as F
from torch import nn

torch.manual_seed(42)
B, T, C = 4, 8, 32
x = torch.randn(B, T, C)
print(x[0, 1])


# idea is to calculate scores or affinity based on previous token values
# it can be simple average of previous tokens in time dimention but that
# can each previous token is not equally contribute to next so we use
# query, key values for each token to find affinity

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False )
value = nn.Linear(C, head_size, bias=False)

k = key(x) # (B, T, head_size)
q = query(x) # (B, T, head_size)
v = value(x) #( B, T, head_size)


print(f'key {k[0,0]}')
print(f'query {q[0, 0]}')
print(f'value {v[0, 0]}')

kt = k.transpose(-2, -1) # (B, head_size, T)
print(f'kt shape {kt.shape}')

w = q @ kt * head_size ** -0.5 #(B, T, head_size @ B, head_size, T) -> B, T, T
print(f'w variance {w.var()}')

print(w.shape)
tril = torch.tril(torch.ones(T, T))

print(tril)
# w = torch.zeros( (T, T))

# create a mask so future tokens don't contribute
w = w.masked_fill(tril == 0, float('-inf'))
print(w[0])
w = F.softmax(w, dim=-1)
print(w [0])
out = w @ v
print(out.shape)

tensor([-1.3847, -0.8712, -0.2234,  1.7174,  0.3189, -0.4245,  0.3057, -0.7746,
        -1.5576,  0.9956, -0.8798, -0.6011, -1.2742,  2.1228, -1.2347, -0.4879,
        -0.9138, -0.6581,  0.0780,  0.5258, -0.4880,  1.1914, -0.8140, -0.7360,
        -1.4032,  0.0360, -0.0635,  0.6756, -0.0978,  1.8446, -1.1845,  1.3835])
key tensor([ 0.0708, -0.9486, -0.5998, -0.8868,  0.0473, -0.0051, -0.0067,  0.6485,
        -0.3294,  0.6546, -0.3531,  0.3808,  0.3335, -0.1976, -0.1575, -0.3816],
       grad_fn=<SelectBackward0>)
query tensor([-0.4467,  0.6160, -0.5806, -0.4032, -1.2520, -0.3569,  0.3134, -0.7361,
         0.9993,  0.0667, -0.5147,  0.0405,  0.2954, -0.2314, -0.5547,  0.0771],
       grad_fn=<SelectBackward0>)
value tensor([ 0.7630, -0.2412, -0.4150,  0.3833,  0.5740, -1.6738,  0.7954,  0.6872,
        -0.3848,  0.5073, -0.5312, -0.1221,  0.0445,  1.2169,  0.9940,  1.5281],
       grad_fn=<SelectBackward0>)
kt shape torch.Size([4, 16, 8])
w variance 0.12312240898609161
torch.Size([4, 